CREATE TABLE IF NOT EXISTS Community(
 Comm_id  int NOT NULL AUTO_INCREMENT,
 Comm_Name varchar(500),
 G_id int NOT NULL,
 U_id int NOT NULL,
 C_id int NOT NULL,
 PRIMARY KEY (Comm_id,G_id,U_id,C_id),
 FOREIGN KEY (U_id) REFERENCES Users(U_id) ON DELETE CASCADE,
 FOREIGN KEY (C_id) REFERENCES Comments(C_id) ON DELETE CASCADE,
 FOREIGN KEY (G_id) REFERENCES Game(G_id) ON DELETE CASCADE
)ENGINE=InnoDB  AUTO_INCREMENT=1;

